version: '3.5'

services:
#  web:
#    build: .
#    ports:
#      - "8000:8000"

  postgres:
    container_name: postgres_test
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - "5431:5431"
    #    volumes:
    #      - pg_data:/var/lib/postgres/data
    restart: always