version: '3.5'

services:
#  web:
#    build: .
#    ports:
#      - "8000:8000"

  postgres:
    container_name: postgres_testcase
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    #    volumes:
    #      - pg_data:/var/lib/postgres/data
    restart: always